


const TEST_CONST = "testttttt"

for (spawnName in Game.spawns) {
  global.heap.userName = Game.spawns[spawnName].owner.username
  break;
}
const USERNAME = global.heap.userName
const SIGN_TEXT = 'What are you ? To define is to limit'
//CPU/Benchmarking 
const AVG_STEP = 5000


//Room states
const STATE_UNDER_ATTACK='under_attack'
const STATE_NEED_ENERGY='need_energy'


//Creep Roles
const ROLE_HARVESTER = 'harvester'
const ROLE_CARRIER = 'carrier'
const ROLE_FILLER = 'filler'
const ROLE_SOLDIER = 'soldier'
const ROLE_SCOUT = 'scout'
const ROLE_WORKER = 'worker'
const ROLE_REPAIRER = 'repairer'
const ROLE_HAULER = 'hauler'
const ROLE_RESERVER = 'reserver'
const ROLE_RAMPART_REPAIRER = 'rampart_repairer'
const ROLE_RESOURCE_MANAGER = 'resource_manager'
const ROLE_CLAIMER = 'claimer'
const ROLE_COLONIZER = 'colonizer'
const ROLE_MINER = 'miner'
const ROLE_MINERAL_CARRIER = 'mineral_carrier'
const ROLE_DOCTOR = 'doctor'

const ROLE_ENERGY_DRAINER='energy_drainer'

const ROLE_QUAD_MEMBER = 'quad_member'
const RANGED_BODY = 'ranged_body'
const HEALER_BODY = 'healer_body'

//Creep constants
const CREEP_MAX_BODYPARTS = 50; // maximum creep body length - couldn't find in API
const CREEP_TICKS_TO_LIVE_BUFFER=100
const HAULER_REQ_CARRY_PARTS = 6;
const DEFAULT_COLONIZERS_AMOUNT = 4;
const RAMPARTS_REPAIRERS_FACTOR=0.75

//Creeps tasks
const TASK_HARVEST = 'harvest'
const TASK_UPGRADE = 'upgrade'
const TASK_BUILD = 'build'
const TASK_COLLECT = 'collect'
const TASK_COLLECT_MINERAL = 'collect_mineral'
const TASK_STORE_MINERAL = 'store_mineral'
const TASK_FILL_UPGRADERS_CONTAIER = 'fill_upgraders_container'
const TASK_FILL_EXTENSIONS = 'fill_extensions'
const TASK_FILL_SPAWN = 'fill_spawn'
const TASK_REPAIR_RAMPARTS = 'repair_ramparts'
const TASK_FILL_TERMINAL_ENERGY = 'fill_terminal_energy'
const TASK_FILL_STORAGE_ENERGY = 'fill_storage_energy'
const TASK_FILL_LINK = 'fill_link'
const TASK_FILL_FILLERS_CONTAINERS='fill_fillers_containers'
const TASK_TAKE_FROM_LINK = 'take_from_link'
const TASK_FILL_MANAGER_LINK = 'fill_manager_link'
const TASK_FILL_NUKER_GHODIUM = 'fill_nuker_ghodium'
const TASK_FILL_NUKER_ENERGY = 'fill_nuker_energy'
const TASK_CLEAR_CREEP = 'clear_creep'
const TASK_FILL_LAB_ENERGY = 'fill_lab_energy'
const TASK_FILL_INPUT_LAB_1_ENERGY = 'fill_input_lab_1_energy'
const TASK_FILL_INPUT_LAB_2_ENERGY = 'fill_input_lab_2_energy'
const TASK_BOOST_CREEP = 'task_boost_creep'
const TASK_FILL_INPUT_LABS_MINERAL = 'fill_input_labs_mineral'
const TASK_CLEAR_INPUT_LABS = 'cl_input_labs'
const TASK_CLEAR_OUTPUT_LABS = 'cl_output_labs'



const REVERSED_RESOURCE = {
  energy: "RESOURCE_ENERGY",
  power: "RESOURCE_POWER",

  H: "RESOURCE_HYDROGEN",
  O: "RESOURCE_OXYGEN",
  U: "RESOURCE_UTRIUM",
  L: "RESOURCE_LEMERGIUM",
  K: "RESOURCE_KEANIUM",
  Z: "RESOURCE_ZYNTHIUM",
  X: "RESOURCE_CATALYST",
  G: "RESOURCE_GHODIUM",

  silicon: "RESOURCE_SILICON",
  metal: "RESOURCE_METAL",
  biomass: "RESOURCE_BIOMASS",
  mist: "RESOURCE_MIST",

  OH: "RESOURCE_HYDROXIDE",
  ZK: "RESOURCE_ZYNTHIUM_KEANITE",
  UL: "RESOURCE_UTRIUM_LEMERGITE",

  UH: "RESOURCE_UTRIUM_HYDRIDE",
  UO: "RESOURCE_UTRIUM_OXIDE",
  KH: "RESOURCE_KEANIUM_HYDRIDE",
  KO: "RESOURCE_KEANIUM_OXIDE",
  LH: "RESOURCE_LEMERGIUM_HYDRIDE",
  LO: "RESOURCE_LEMERGIUM_OXIDE",
  ZH: "RESOURCE_ZYNTHIUM_HYDRIDE",
  ZO: "RESOURCE_ZYNTHIUM_OXIDE",
  GH: "RESOURCE_GHODIUM_HYDRIDE",
  GO: "RESOURCE_GHODIUM_OXIDE",

  UH2O: "RESOURCE_UTRIUM_ACID",
  UHO2: "RESOURCE_UTRIUM_ALKALIDE",
  KH2O: "RESOURCE_KEANIUM_ACID",
  KHO2: "RESOURCE_KEANIUM_ALKALIDE",
  LH2O: "RESOURCE_LEMERGIUM_ACID",
  LHO2: "RESOURCE_LEMERGIUM_ALKALIDE",
  ZH2O: "RESOURCE_ZYNTHIUM_ACID",
  ZHO2: "RESOURCE_ZYNTHIUM_ALKALIDE",
  GH2O: "RESOURCE_GHODIUM_ACID",
  GHO2: "RESOURCE_GHODIUM_ALKALIDE",

  XUH2O: "RESOURCE_CATALYZED_UTRIUM_ACID",
  XUHO2: "RESOURCE_CATALYZED_UTRIUM_ALKALIDE",
  XKH2O: "RESOURCE_CATALYZED_KEANIUM_ACID",
  XKHO2: "RESOURCE_CATALYZED_KEANIUM_ALKALIDE",
  XLH2O: "RESOURCE_CATALYZED_LEMERGIUM_ACID",
  XLHO2: "RESOURCE_CATALYZED_LEMERGIUM_ALKALIDE",
  XZH2O: "RESOURCE_CATALYZED_ZYNTHIUM_ACID",
  XZHO2: "RESOURCE_CATALYZED_ZYNTHIUM_ALKALIDE",
  XGH2O: "RESOURCE_CATALYZED_GHODIUM_ACID",
  XGHO2: "RESOURCE_CATALYZED_GHODIUM_ALKALIDE",

  ops: "RESOURCE_OPS",

  utrium_bar: "RESOURCE_UTRIUM_BAR",
  lemergium_bar: "RESOURCE_LEMERGIUM_BAR",
  zynthium_bar: "RESOURCE_ZYNTHIUM_BAR",
  keanium_bar: "RESOURCE_KEANIUM_BAR",
  ghodium_melt: "RESOURCE_GHODIUM_MELT",
  oxidant: "RESOURCE_OXIDANT",
  reductant: "RESOURCE_REDUCTANT",
  purifier: "RESOURCE_PURIFIER",
  battery: "RESOURCE_BATTERY",

  composite: "RESOURCE_COMPOSITE",
  crystal: "RESOURCE_CRYSTAL",
  liquid: "RESOURCE_LIQUID",

  wire: "RESOURCE_WIRE",
  switch: "RESOURCE_SWITCH",
  transistor: "RESOURCE_TRANSISTOR",
  microchip: "RESOURCE_MICROCHIP",
  circuit: "RESOURCE_CIRCUIT",
  device: "RESOURCE_DEVICE",

  cell: "RESOURCE_CELL",
  phlegm: "RESOURCE_PHLEGM",
  tissue: "RESOURCE_TISSUE",
  muscle: "RESOURCE_MUSCLE",
  organoid: "RESOURCE_ORGANOID",
  organism: "RESOURCE_ORGANISM",

  alloy: "RESOURCE_ALLOY",
  tube: "RESOURCE_TUBE",
  fixtures: "RESOURCE_FIXTURES",
  frame: "RESOURCE_FRAME",
  hydraulics: "RESOURCE_HYDRAULICS",
  machine: "RESOURCE_MACHINE",

  condensate: "RESOURCE_CONDENSATE",
  concentrate: "RESOURCE_CONCENTRATE",
  extract: "RESOURCE_EXTRACT",
  spirit: "RESOURCE_SPIRIT",
  emanation: "RESOURCE_EMANATION",
  essence: "RESOURCE_ESSENCE",
};

const RESOURCES = {
  RESOURCE_ENERGY: 'energy',
  RESOURCE_POWER: "power",

  RESOURCE_HYDROGEN: "H",
  RESOURCE_OXYGEN: "O",
  RESOURCE_UTRIUM: "U",
  RESOURCE_LEMERGIUM: "L",
  RESOURCE_KEANIUM: "K",
  RESOURCE_ZYNTHIUM: "Z",
  RESOURCE_CATALYST: "X",
  RESOURCE_GHODIUM: "G",

  
  RESOURCE_SILICON: "silicon",
  RESOURCE_METAL: "metal",
  RESOURCE_BIOMASS: "biomass",
  RESOURCE_MIST: "mist",

  RESOURCE_HYDROXIDE: "OH",
  RESOURCE_ZYNTHIUM_KEANITE: "ZK",
  RESOURCE_UTRIUM_LEMERGITE: "UL",

  RESOURCE_UTRIUM_HYDRIDE: "UH",
  RESOURCE_UTRIUM_OXIDE: "UO",
  RESOURCE_KEANIUM_HYDRIDE: "KH",
  RESOURCE_KEANIUM_OXIDE: "KO",
  RESOURCE_LEMERGIUM_HYDRIDE: "LH",
  RESOURCE_LEMERGIUM_OXIDE: "LO",
  RESOURCE_ZYNTHIUM_HYDRIDE: "ZH",
  RESOURCE_ZYNTHIUM_OXIDE: "ZO",
  RESOURCE_GHODIUM_HYDRIDE: "GH",
  RESOURCE_GHODIUM_OXIDE: "GO",

  RESOURCE_UTRIUM_ACID: "UH2O",
  RESOURCE_UTRIUM_ALKALIDE: "UHO2",
  RESOURCE_KEANIUM_ACID: "KH2O",
  RESOURCE_KEANIUM_ALKALIDE: "KHO2",
  RESOURCE_LEMERGIUM_ACID: "LH2O",
  RESOURCE_LEMERGIUM_ALKALIDE: "LHO2",
  RESOURCE_ZYNTHIUM_ACID: "ZH2O",
  RESOURCE_ZYNTHIUM_ALKALIDE: "ZHO2",
  RESOURCE_GHODIUM_ACID: "GH2O",
  RESOURCE_GHODIUM_ALKALIDE: "GHO2",

  RESOURCE_CATALYZED_UTRIUM_ACID: "XUH2O",
  RESOURCE_CATALYZED_UTRIUM_ALKALIDE: "XUHO2",
  RESOURCE_CATALYZED_KEANIUM_ACID: "XKH2O",
  RESOURCE_CATALYZED_KEANIUM_ALKALIDE: "XKHO2",
  RESOURCE_CATALYZED_LEMERGIUM_ACID: "XLH2O",
  RESOURCE_CATALYZED_LEMERGIUM_ALKALIDE: "XLHO2",
  RESOURCE_CATALYZED_ZYNTHIUM_ACID: "XZH2O",
  RESOURCE_CATALYZED_ZYNTHIUM_ALKALIDE: "XZHO2",
  RESOURCE_CATALYZED_GHODIUM_ACID: "XGH2O",
  RESOURCE_CATALYZED_GHODIUM_ALKALIDE: "XGHO2",

  RESOURCE_OPS: "ops",

  RESOURCE_UTRIUM_BAR: "utrium_bar",
  RESOURCE_LEMERGIUM_BAR: "lemergium_bar",
  RESOURCE_ZYNTHIUM_BAR: "zynthium_bar",
  RESOURCE_KEANIUM_BAR: "keanium_bar",
  RESOURCE_GHODIUM_MELT: "ghodium_melt",
  RESOURCE_OXIDANT: "oxidant",
  RESOURCE_REDUCTANT: "reductant",
  RESOURCE_PURIFIER: "purifier",
  RESOURCE_BATTERY: "battery",

  RESOURCE_COMPOSITE: "composite",
  RESOURCE_CRYSTAL: "crystal",
  RESOURCE_LIQUID: "liquid",

  RESOURCE_WIRE: "wire",
  RESOURCE_SWITCH: "switch",
  RESOURCE_TRANSISTOR: "transistor",
  RESOURCE_MICROCHIP: "microchip",
  RESOURCE_CIRCUIT: "circuit",
  RESOURCE_DEVICE: "device",

  RESOURCE_CELL: "cell",
  RESOURCE_PHLEGM: "phlegm",
  RESOURCE_TISSUE: "tissue",
  RESOURCE_MUSCLE: "muscle",
  RESOURCE_ORGANOID: "organoid",
  RESOURCE_ORGANISM: "organism",

  RESOURCE_ALLOY: "alloy",
  RESOURCE_TUBE: "tube",
  RESOURCE_FIXTURES: "fixtures",
  RESOURCE_FRAME: "frame",
  RESOURCE_HYDRAULICS: "hydraulics",
  RESOURCE_MACHINE: "machine",

  RESOURCE_CONDENSATE: "condensate",
  RESOURCE_CONCENTRATE: "concentrate",
  RESOURCE_EXTRACT: "extract",
  RESOURCE_SPIRIT: "spirit",
  RESOURCE_EMANATION: "emanation",
  RESOURCE_ESSENCE: "essence"
  
};




const TASK_TRANSFER_TO_STORAGE = {
  [RESOURCE_ENERGY]: "transfer_to_storage_energy",
  [RESOURCE_POWER]: "transfer_to_storage_power",

  [RESOURCE_HYDROGEN]: "transfer_to_storage_H",
  [RESOURCE_OXYGEN]: "transfer_to_storage_O",
  [RESOURCE_UTRIUM]: "transfer_to_storage_U",
  [RESOURCE_LEMERGIUM]: "transfer_to_storage_L",
  [RESOURCE_KEANIUM]: "transfer_to_storage_K",
  [RESOURCE_ZYNTHIUM]: "transfer_to_storage_Z",
  [RESOURCE_CATALYST]: "transfer_to_storage_X",
  [RESOURCE_GHODIUM]: "transfer_to_storage_G",

  [RESOURCE_SILICON]: "transfer_to_storage_silicon",
  [RESOURCE_METAL]: "transfer_to_storage_metal",
  [RESOURCE_BIOMASS]: "transfer_to_storage_biomass",
  [RESOURCE_MIST]: "transfer_to_storage_mist",

  [RESOURCE_HYDROXIDE]: "transfer_to_storage_OH",
  [RESOURCE_ZYNTHIUM_KEANITE]: "transfer_to_storage_ZK",
  [RESOURCE_UTRIUM_LEMERGITE]: "transfer_to_storage_UL",

  [RESOURCE_UTRIUM_HYDRIDE]: "transfer_to_storage_UH",
  [RESOURCE_UTRIUM_OXIDE]: "transfer_to_storage_UO",
  [RESOURCE_KEANIUM_HYDRIDE]: "transfer_to_storage_KH",
  [RESOURCE_KEANIUM_OXIDE]: "transfer_to_storage_KO",
  [RESOURCE_LEMERGIUM_HYDRIDE]: "transfer_to_storage_LH",
  [RESOURCE_LEMERGIUM_OXIDE]: "transfer_to_storage_LO",
  [RESOURCE_ZYNTHIUM_HYDRIDE]: "transfer_to_storage_ZH",
  [RESOURCE_ZYNTHIUM_OXIDE]: "transfer_to_storage_ZO",
  [RESOURCE_GHODIUM_HYDRIDE]: "transfer_to_storage_GH",
  [RESOURCE_GHODIUM_OXIDE]: "transfer_to_storage_GO",

  [RESOURCE_UTRIUM_ACID]: "transfer_to_storage_UH2O",
  [RESOURCE_UTRIUM_ALKALIDE]: "transfer_to_storage_UHO2",
  [RESOURCE_KEANIUM_ACID]: "transfer_to_storage_KH2O",
  [RESOURCE_KEANIUM_ALKALIDE]: "transfer_to_storage_KHO2",
  [RESOURCE_LEMERGIUM_ACID]: "transfer_to_storage_LH2O",
  [RESOURCE_LEMERGIUM_ALKALIDE]: "transfer_to_storage_LHO2",
  [RESOURCE_ZYNTHIUM_ACID]: "transfer_to_storage_ZH2O",
  [RESOURCE_ZYNTHIUM_ALKALIDE]: "transfer_to_storage_ZHO2",
  [RESOURCE_GHODIUM_ACID]: "transfer_to_storage_GH2O",
  [RESOURCE_GHODIUM_ALKALIDE]: "transfer_to_storage_GHO2",

  [RESOURCE_CATALYZED_UTRIUM_ACID]: "transfer_to_storage_XUH2O",
  [RESOURCE_CATALYZED_UTRIUM_ALKALIDE]: "transfer_to_storage_XUHO2",
  [RESOURCE_CATALYZED_KEANIUM_ACID]: "transfer_to_storage_XKH2O",
  [RESOURCE_CATALYZED_KEANIUM_ALKALIDE]: "transfer_to_storage_XKHO2",
  [RESOURCE_CATALYZED_LEMERGIUM_ACID]: "transfer_to_storage_XLH2O",
  [RESOURCE_CATALYZED_LEMERGIUM_ALKALIDE]: "transfer_to_storage_XLHO2",
  [RESOURCE_CATALYZED_ZYNTHIUM_ACID]: "transfer_to_storage_XZH2O",
  [RESOURCE_CATALYZED_ZYNTHIUM_ALKALIDE]: "transfer_to_storage_XZHO2",
  [RESOURCE_CATALYZED_GHODIUM_ACID]: "transfer_to_storage_XGH2O",
  [RESOURCE_CATALYZED_GHODIUM_ALKALIDE]: "transfer_to_storage_XGHO2",
};


const TASK_TRANSFER_TO_TERMINAL = {
  [RESOURCE_ENERGY]: "transfer_to_terminal_energy",
  [RESOURCE_POWER]: "transfer_to_terminal_power",

  [RESOURCE_HYDROGEN]: "transfer_to_terminal_H",
  [RESOURCE_OXYGEN]: "transfer_to_terminal_O",
  [RESOURCE_UTRIUM]: "transfer_to_terminal_U",
  [RESOURCE_LEMERGIUM]: "transfer_to_terminal_L",
  [RESOURCE_KEANIUM]: "transfer_to_terminal_K",
  [RESOURCE_ZYNTHIUM]: "transfer_to_terminal_Z",
  [RESOURCE_CATALYST]: "transfer_to_terminal_X",
  [RESOURCE_GHODIUM]: "transfer_to_terminal_G",

  [RESOURCE_SILICON]: "transfer_to_terminal_silicon",
  [RESOURCE_METAL]: "transfer_to_terminal_metal",
  [RESOURCE_BIOMASS]: "transfer_to_terminal_biomass",
  [RESOURCE_MIST]: "transfer_to_terminal_mist",

  [RESOURCE_HYDROXIDE]: "transfer_to_terminal_OH",
  [RESOURCE_ZYNTHIUM_KEANITE]: "transfer_to_terminal_ZK",
  [RESOURCE_UTRIUM_LEMERGITE]: "transfer_to_terminal_UL",

  [RESOURCE_UTRIUM_HYDRIDE]: "transfer_to_terminal_UH",
  [RESOURCE_UTRIUM_OXIDE]: "transfer_to_terminal_UO",
  [RESOURCE_KEANIUM_HYDRIDE]: "transfer_to_terminal_KH",
  [RESOURCE_KEANIUM_OXIDE]: "transfer_to_terminal_KO",
  [RESOURCE_LEMERGIUM_HYDRIDE]: "transfer_to_terminal_LH",
  [RESOURCE_LEMERGIUM_OXIDE]: "transfer_to_terminal_LO",
  [RESOURCE_ZYNTHIUM_HYDRIDE]: "transfer_to_terminal_ZH",
  [RESOURCE_ZYNTHIUM_OXIDE]: "transfer_to_terminal_ZO",
  [RESOURCE_GHODIUM_HYDRIDE]: "transfer_to_terminal_GH",
  [RESOURCE_GHODIUM_OXIDE]: "transfer_to_terminal_GO",

  [RESOURCE_UTRIUM_ACID]: "transfer_to_terminal_UH2O",
  [RESOURCE_UTRIUM_ALKALIDE]: "transfer_to_terminal_UHO2",
  [RESOURCE_KEANIUM_ACID]: "transfer_to_terminal_KH2O",
  [RESOURCE_KEANIUM_ALKALIDE]: "transfer_to_terminal_KHO2",
  [RESOURCE_LEMERGIUM_ACID]: "transfer_to_terminal_LH2O",
  [RESOURCE_LEMERGIUM_ALKALIDE]: "transfer_to_terminal_LHO2",
  [RESOURCE_ZYNTHIUM_ACID]: "transfer_to_terminal_ZH2O",
  [RESOURCE_ZYNTHIUM_ALKALIDE]: "transfer_to_terminal_ZHO2",
  [RESOURCE_GHODIUM_ACID]: "transfer_to_terminal_GH2O",
  [RESOURCE_GHODIUM_ALKALIDE]: "transfer_to_terminal_GHO2",

  [RESOURCE_CATALYZED_UTRIUM_ACID]: "transfer_to_terminal_XUH2O",
  [RESOURCE_CATALYZED_UTRIUM_ALKALIDE]: "transfer_to_terminal_XUHO2",
  [RESOURCE_CATALYZED_KEANIUM_ACID]: "transfer_to_terminal_XKH2O",
  [RESOURCE_CATALYZED_KEANIUM_ALKALIDE]: "transfer_to_terminal_XKHO2",
  [RESOURCE_CATALYZED_LEMERGIUM_ACID]: "transfer_to_terminal_XLH2O",
  [RESOURCE_CATALYZED_LEMERGIUM_ALKALIDE]: "transfer_to_terminal_XLHO2",
  [RESOURCE_CATALYZED_ZYNTHIUM_ACID]: "transfer_to_terminal_XZH2O",
  [RESOURCE_CATALYZED_ZYNTHIUM_ALKALIDE]: "transfer_to_terminal_XZHO2",
  [RESOURCE_CATALYZED_GHODIUM_ACID]: "transfer_to_terminal_XGH2O",
  [RESOURCE_CATALYZED_GHODIUM_ALKALIDE]: "transfer_to_terminal_XGHO2",
};




//Economy const
const MAX_SOURCE_DISTANCE=150;
const BALANCER_STEP = 1// value by which workers and carriers change value of balancer
const BALANCER_WORKER_STEP = 3
const BALANCER_CARRIER_STEP = 1
const BALANCER_DECAY = 10 // natural decay towards 0 of balancer
const BALANCER_HARVEST_LIMIT = 1000.0 // harvesting limit of balancer - if that would go too high then it would take a lot of time to switch to using energy
const BALANCER_USE_LIMIT = 1000 // carrying balancer of balancer
const UPGRADE_FACTOR_1 =20000//smaller number here means more workers drastically
const UPGRADE_FACTOR_2=20//smaller number here means more workers
const STORAGE_BALANCER_START = 50000
const ENERGY_BALANCER_UPGRADER_START = 50
const ENERGY_BALANCER_WORKER_SPAWN = 750
const HARVESTING_BODYPARTS_FRACTION = 0.6 // fraction of body parts that we destinate to gather (harvest and carry) energy
const CONTROLLER_DOWNGRADE_BOTTOM_LIMIT = 0.3 // below that percentage of downgrade workers will ignore construction sites
const CONTROLLER_DOWNGRADE_TOP_LIMIT = 0.8
const STORAGE_ENERGY_UPGRADE_LIMIT = 5000 // below that amount workers wouldn't take energy from storage
const RAMPART_HITS_BOTTOM_LIMIT = 5000
const TOWER_BOTTOM_LIMIT = 0.4
const TOWER_UP_LIMIT = 0.8
const RAMPART_DECAY_LIMIT = 40
const TERMINAL_BOTTOM_ENERGY = 30000
const TERMINAL_TOP_ENERGY = 40000
const TERMINAL_FREE_BUFFER = 10000
const TERMINAL_FASTRCL_FREE_BUFFER = 1000
const STORAGE_TOP_ENERGY = 150000
const STORAGE_FASTRCL_BOTTOM_ENERGY = 40000
const STORAGE_ENERGY_BOTTOM = 50000
const STORAGE_ENERGY_BUY_BOTTOM=20000
const STORAGE_ENERGY_TOP=700000
const LINEAR_WORKERS_AMOUNT_ENERGY_EDGE=STORAGE_TOP_ENERGY+UPGRADE_FACTOR_1
const LINK_BOTTOM_ENERGY = LINK_CAPACITY * (2 / 8)
const LINK_TOP_ENERGY = LINK_CAPACITY * (7 / 8)
const LINK_FREE_SPACE=LINK_CAPACITY*(1/8)
const COLONIZE_ENERGY_LIMIT = 40000
const MIN_RAW_RESOURCE_AMOUNT = 20000
const MAX_RAW_RESOURCE_AMOUNT = 60000
const RESOURCE_SHARE_AMOUNT = 5000
const RAW_RES_BUY_AMOUNT = 10000;
const RAW_RES_SELL_AMOUNT = 5000;
const MIN_ECONOMIC_BOOST_AMOUNT = 10000
const MIN_MILITARY_BOOST_AMOUNT = 30000
const REACTION_STEP = 500
const MIN_NUKER_RES_AMOUNT = 100 // minimum amount of energy or ghodium in storage/temrinal to consider transfering it to nuker
const ROOM_DISTANCE_CALC_STEP = 1
const DOCTOR_MIN_REMAINING_TIME=20
const STRUCTURE_ONLY_ATTACK_POWER=500
const RAMPART_MIN_WORKER_HITS=RAMPART_DECAY_AMOUNT*10

// Room attack
const ROOM_ATTACK_HISTORY_RANGE = 500



// Room Visualization
const OUTLINE_COLOR = 'black'
const TEXT_COLOR = '#fc03b6'
const FILL_COLOR = 'grey'

// Room Layout Variations
const SRC_1 = 'src_1'
const SRC_2 = 'src_2'
const SRC_1_2 = 'src_1_2'
const SRC_1_CONTROLLER = 'src_1_controller'
const SRC_2_CONTROLLER = 'src_2_controller'
const SRC_1_2_CONTROLLER = 'src_1_2_controller'
const CONTROLLER = 'controller'
const CURRENT_SPAWNPOS = 'spawn_position'
const LAYOUT = {
  SRC_1: 'src_1',
  SRC_2: 'src_2',
  SRC_1_2: 'src_1_2',
  SRC_1_CONTROLLER: 'src_1_controller',
  SRC_2_CONTROLLER: 'src_2_controller',
  SRC_1_2_CONTROLLER: 'src_1_2_controller',
}
const BUILD_TIME_STEP = 2

const ATTACK_TYPE_QUAD = 'attack_type_quad'
const ATTACK_TYPE_DUO = 'attack_type_duo'
const ATTACK_TYPE_SINGLE = 'attack_type_single'
const ATTACK_TYPE_ENERGY_DRAIN = 'attack_type_energy_drain'
const ATTACK_TYPE_DISMANTLE = 'attack_type_dismantle'
const ATTACK_TYPE_CONTROLLER_DOWNGRADE = 'attack_type_controller_downgrade'
const ATTACK_TYPE_NUKE = 'attack_type_nuke'
const ATTACK_TYPE_SCOUT = 'attack_type_scout'
const ATTACK_TYPE_PLUNDER = 'attack_type_plunder'// collecting resources from structures
const MAX_ROOM_INVISIBILITY_TIME=3000

const QUAD_BODY_PARTS_AMOUNT = 200
const MIN_QUAD_MEMBER_BODY_LENGTH=50

module.exports = {
  TEST_CONST,
  AVG_STEP,
  SIGN_TEXT,
  USERNAME,
  STATE_UNDER_ATTACK,
  STATE_NEED_ENERGY,
  ROLE_HARVESTER,
  ROLE_CARRIER,
  ROLE_FILLER,
  ROLE_SOLDIER,
  ROLE_SCOUT,
  ROLE_WORKER,
  ROLE_REPAIRER,
  ROLE_HAULER,
  ROLE_RESERVER,
  ROLE_RAMPART_REPAIRER,
  ROLE_RESOURCE_MANAGER,
  ROLE_CLAIMER,
  ROLE_COLONIZER,
  ROLE_MINER,
  ROLE_MINERAL_CARRIER,
  ROLE_DOCTOR,
  ROLE_ENERGY_DRAINER,

  ROLE_QUAD_MEMBER,
  RANGED_BODY,
  HEALER_BODY,

  CREEP_MAX_BODYPARTS,
  CREEP_TICKS_TO_LIVE_BUFFER,
  HAULER_REQ_CARRY_PARTS,
  DEFAULT_COLONIZERS_AMOUNT,
  RAMPARTS_REPAIRERS_FACTOR,

  TASK_HARVEST,
  TASK_UPGRADE,
  TASK_BUILD,
  TASK_COLLECT,
  TASK_COLLECT_MINERAL,
  TASK_STORE_MINERAL,
  TASK_FILL_UPGRADERS_CONTAIER,
  TASK_FILL_EXTENSIONS,
  TASK_FILL_SPAWN,
  TASK_REPAIR_RAMPARTS,
  TASK_FILL_TERMINAL_ENERGY,
  TASK_FILL_LINK,
  TASK_TAKE_FROM_LINK,
  TASK_FILL_FILLERS_CONTAINERS,
  REVERSED_RESOURCE,
  RESOURCES,
  TASK_TRANSFER_TO_STORAGE,
  TASK_TRANSFER_TO_TERMINAL,
  TASK_FILL_MANAGER_LINK,
  TASK_FILL_NUKER_GHODIUM,
  TASK_FILL_NUKER_ENERGY,

  TASK_CLEAR_CREEP,
  TASK_FILL_LAB_ENERGY,
  TASK_FILL_INPUT_LAB_1_ENERGY,
  TASK_FILL_INPUT_LAB_2_ENERGY,

  TASK_FILL_INPUT_LABS_MINERAL,
  TASK_CLEAR_INPUT_LABS,
  TASK_CLEAR_OUTPUT_LABS,
  TASK_BOOST_CREEP,



  MAX_SOURCE_DISTANCE,
  BALANCER_STEP,
  BALANCER_WORKER_STEP,
  BALANCER_CARRIER_STEP,

  BALANCER_DECAY,
  BALANCER_HARVEST_LIMIT,
  BALANCER_USE_LIMIT,
  UPGRADE_FACTOR_1,
  UPGRADE_FACTOR_2,
  LINEAR_WORKERS_AMOUNT_ENERGY_EDGE,
  STORAGE_BALANCER_START,
  ENERGY_BALANCER_UPGRADER_START,
  ENERGY_BALANCER_WORKER_SPAWN,
  HARVESTING_BODYPARTS_FRACTION,
  CONTROLLER_DOWNGRADE_BOTTOM_LIMIT,
  CONTROLLER_DOWNGRADE_TOP_LIMIT,
  STORAGE_ENERGY_UPGRADE_LIMIT,
  RAMPART_HITS_BOTTOM_LIMIT,
  TOWER_BOTTOM_LIMIT,
  TOWER_UP_LIMIT,
  RAMPART_DECAY_LIMIT,
  TERMINAL_BOTTOM_ENERGY,
  TERMINAL_TOP_ENERGY,
  TERMINAL_FREE_BUFFER,
  TERMINAL_FASTRCL_FREE_BUFFER,
  STORAGE_TOP_ENERGY,
  STORAGE_FASTRCL_BOTTOM_ENERGY,
  STORAGE_ENERGY_BOTTOM,
  STORAGE_ENERGY_BUY_BOTTOM,
  STORAGE_ENERGY_TOP,
  LINK_TOP_ENERGY,
  LINK_BOTTOM_ENERGY,
  LINK_FREE_SPACE,
  LINK_BOTTOM_ENERGY,
  COLONIZE_ENERGY_LIMIT,
  MIN_RAW_RESOURCE_AMOUNT,
  MAX_RAW_RESOURCE_AMOUNT,
  RESOURCE_SHARE_AMOUNT,
  RAW_RES_BUY_AMOUNT,
  RAW_RES_SELL_AMOUNT,
  MIN_ECONOMIC_BOOST_AMOUNT,
  MIN_MILITARY_BOOST_AMOUNT,
  REACTION_STEP,
  MIN_NUKER_RES_AMOUNT,
  ROOM_DISTANCE_CALC_STEP,
  DOCTOR_MIN_REMAINING_TIME,
  STRUCTURE_ONLY_ATTACK_POWER,
  RAMPART_MIN_WORKER_HITS,
  
  ROOM_ATTACK_HISTORY_RANGE,

  OUTLINE_COLOR,
  TEXT_COLOR,
  FILL_COLOR,

  SRC_1,
  SRC_2,
  SRC_1_2,
  CONTROLLER,
  SRC_1_CONTROLLER,
  SRC_2_CONTROLLER,
  SRC_1_2_CONTROLLER,
  CURRENT_SPAWNPOS,
  LAYOUT,

  BUILD_TIME_STEP,

  ATTACK_TYPE_QUAD,
  ATTACK_TYPE_DUO,
  ATTACK_TYPE_SINGLE,
  ATTACK_TYPE_ENERGY_DRAIN,
  ATTACK_TYPE_DISMANTLE,
  ATTACK_TYPE_CONTROLLER_DOWNGRADE,
  ATTACK_TYPE_NUKE,
  ATTACK_TYPE_SCOUT,
  ATTACK_TYPE_PLUNDER,
  MAX_ROOM_INVISIBILITY_TIME,

  QUAD_BODY_PARTS_AMOUNT,
  MIN_QUAD_MEMBER_BODY_LENGTH
};

